# https://www.debian.org/doc/manuals/maint-guide/dother.en.html#install
target/cas.jar opt/atlas/cas
debian/cas.conf opt/atlas/cas
debian/data/cas/config/application.template data/cas/config
debian/data/cas/config/log4j2.xml data/cas/config

# Just an example of db install and update via debian
#mysql.sql usr/share/dbconfig-common/data/ala-cas-5/install/mysql
#mysql-upgrade_2.1.sql usr/share/dbconfig-common/data/ala-cas-5/upgrade/mysql/2.1
